### ISSUE TITLE
'VisualEffectBlur' initializer is inaccessible due to 'internal' protection level on Mac

### ISSUE THREAD

**Issue by EthanLipnik** [twostraws/VisualEffects#5]
`'VisualEffectBlur' initializer is inaccessible due to 'internal' protection level`

macOS Big Sur – Xcode 12 Beta. Multiplatform application. Works on iOS but not on macOS.

**Comment by twostraws** [comment]
Thank you! Could you check with 1.0.1, please?

**Comment by EthanLipnik** [comment]
@twostraws Same issue

**Comment by twostraws** [comment]
We now have 1.0.2, which should fix the issue – better?

**Comment by EthanLipnik** [comment]
Thank you! Seems to work now

**Comment by twostraws** [comment]
Excellent – thanks, @maximkrouk! 👍
