### ISSUE TITLE
Can't add to a project in Xcode 11.5

### ISSUE THREAD

**Issue by EthanLipnik** [twostraws/VisualEffects#6]
`Failed to resolve package dependencies because every version of VisualEffects contains incompatible tools version and root depends on VisualEffects 1.0.2..<2.0.0, version solving failed.`

**Comment by twostraws** [comment]
Yeah, this currently has a `swift-tools-version` setting of 5.3. I could try pushing it down to 5.2 so it opens on Xcode 11, but I'm not sure whether the actual code is fully compatible. Would you be able to test it out?

**Comment by EthanLipnik** [comment]
Sure!

**Comment by twostraws** [comment]
There you go; try pulling from the "main" branch directly.

**Comment by EthanLipnik** [comment]
Works great in 11.5 now! Just forked and added it to my project and it was successful.

**Comment by twostraws** [comment]
Great! I shall tag this now 👍
