### ISSUE TITLE
Original?

### ISSUE THREAD

**Issue by melMass** [twostraws/VisualEffects#8]
Hi Paul,

Thanks for the repo, the mac version seems unfinished, may I ask where did you find these, please?

**Comment by twostraws** [comment]
[Here you go](https://developer.apple.com/documentation/app_clips/fruta_building_a_feature-rich_app_with_swiftui). Note: this whole repository is not needed from iOS 15 and later.

**Comment by melMass** [comment]
Thanks I'm still on Catalina!
